require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task :default => %w[test]
task :test => :spec
task :run do
  require_relative 'lib/guess_number_app.rb'
end